
title: My
url: 'https://oguzhanazari.github.io/'
baseurl: '' #change it according to your repository name


# Enable one of these styles by removing #
#style: styles-2
#style: styles-3
#style: styles-4
style: styles-5
#style: styles-6




#Profile information
name: Oğuzhan Azarı
#tagline: Full Stack Developer
pic: profile1.png #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: ogzhnazr@gmail.com
phone: 0535 370 19 66
website: oguzhanazari.github.io #do not add http://
linkedin: linkedin.com/in/ogzhnazr
github: github.com/oguzhanazari
#twitter: '@twittername'

